apiVersion: v1
kind: Pod
metadata:
  name: ingest
  namespace: online-ml
spec:
  containers:
  - name: ingest
    image: ghcr.io/mentics-online-ml/ingest:latest
    envFrom:
    - configMapRef:
        name: online-ml-config
    - secretRef:
        name: online-ml-secrets
