apiVersion: v1
kind: Pod
metadata:
  name: rust-dev
spec:
  # volumes:
  # - name: shared-data
  #   emptyDir: {}
  containers:
  - name: rust
    image: rust
    # volumeMounts:
    # - name: shared-data
    #   mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default
