name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-and-push-image:
        runs-on: [self-hosted, rust]

        permissions:
          contents: read
          packages: write

        steps:
          - name: "Check some things"
            run: |
              echo "PATH: $PATH"
              echo "RUSTC_WRAPPER: $RUSTC_WRAPPER"

          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Build with cargo'
            run: |
              echo "PATH: $PATH"
              echo "RUSTC_WRAPPER: $RUSTC_WRAPPER"
              sccache --show-stats
              cargo build --release
              sccache --show-stats

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and publish image'
            run: |
              docker build . --tag ghcr.io/mentics-ml-demo/ingest:latest
              docker push ghcr.io/mentics-ml-demo/ingest:latest
