name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: [self-hosted, rust]
        steps:
          - name: "Check some things"
            run: echo "$PATH"

          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Build with cargo'
            run: cargo build --release

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and publish image'
            run: |
              docker build . --tag ghcr.io/mentics-ml-demo/ingest:latest
              docker push ghcr.io/mentics-ml-demo/ingest:latest
