name: Build and deploy to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: [self-hosted, rust]

    permissions:
      contents: read
      packages: write

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: "sccache stats before"
      run: sccache --show-stats

    - name: 'Build with cargo'
      run: RUSTFLAGS='-C link-arg=-s' cargo build --release --target aarch64-unknown-linux-musl

    - name: "sccache stats after"
      run: sccache --show-stats

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build and publish image'
      run: |
        docker build . --tag ghcr.io/mentics-ml-demo/ingest:latest
        docker push ghcr.io/mentics-ml-demo/ingest:latest
